"""核心数据模型模块。

该模块负责声明所有跨层共享的枚举与数据结构，不包含业务逻辑。
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional

from PIL import Image


class Platform(str, Enum):
    """支持的音乐平台枚举。"""

    NCM = "ncm"
    QQ = "qq"
    AM = "am"


class Mode(str, Enum):
    """卡片生成模式枚举。"""

    DAILY = "daily"
    CARD = "card"
    LYRIC = "lyric"
    NOW_PLAYING = "now-playing"


@dataclass
class SongInfo:
    """歌曲基础信息。"""

    title: str
    artist: str
    cover_url: str
    music_id: str
    song_url: Optional[str] = None


@dataclass
class QuoteData:
    """引言信息。"""

    content: str
    source: str


@dataclass
class NowPlayingData:
    """Now Playing 模式输入数据。"""

    progress_ms: int
    duration_ms: int
    track: str
    artist: str
    cover_url: str
    song_url: Optional[str] = None


@dataclass
class CardStyle:
    """卡片配色与文案样式配置。"""

    main: str = "#2A2A2A"
    sub: str = "#555555"
    quote: str = "#4A4A4A"
    accent: str = "#D0D0D0"
    footer_center: str = "#555555"
    watermark_designed: str = "Designed by HamuChan"
    watermark_generated: str = "Generated by KhBot v1.6.2"


@dataclass
class CardLayout:
    """卡片布局尺寸配置。"""

    width: int = 1000
    margin_top: int = 40
    margin_side: int = 40
    margin_bottom: int = 90
    inner_pad: int = 40

    @property
    def card_width(self) -> int:
        """卡片主体宽度。"""
        return self.width - (self.margin_side * 2)

    @property
    def content_left_x(self) -> int:
        """正文左侧坐标。"""
        return self.margin_side + self.inner_pad

    @property
    def content_right_x(self) -> int:
        """正文右侧坐标。"""
        return self.margin_side + self.card_width - self.inner_pad

    @property
    def max_text_width(self) -> int:
        """文本可用最大宽度。"""
        return self.card_width - (self.inner_pad * 2)


@dataclass
class CardRequest:
    """生成卡片的输入参数。"""

    platform: Platform = Platform.NCM
    mode: Mode = Mode.DAILY
    date_str: str = field(default_factory=lambda: datetime.now().strftime("%Y-%m-%d"))
    music_id: Optional[str] = None
    song_info: Optional[SongInfo] = None
    quote: Optional[QuoteData] = None
    now_playing: Optional[NowPlayingData] = None
    now_playing_json: Optional[str] = None
    now_playing_data_url: Optional[str] = None
    inner_blurred: bool = False
    show_qrcode: bool = False
    font_path: str = "PingFang.ttc"
    am_storefront: str = "cn"
    style: CardStyle = field(default_factory=CardStyle)
    layout: CardLayout = field(default_factory=CardLayout)


@dataclass
class CardResult:
    """生成卡片的返回结果。"""

    success: bool
    image: Optional[Image.Image] = None
    music_id: Optional[str] = None
    error_code: Optional[str] = None
    message: str = ""


@dataclass
class DailyRecommendation:
    """每日推荐接口返回的核心字段。"""

    music_id: Optional[str]
    date: Optional[str]
    username: Optional[str]
    comment: Optional[str]
    cover_path: Optional[str]


@dataclass
class QuoteLine:
    """解析后的单行引言。"""

    spec: Optional[str]
    text: str


@dataclass
class QuoteParseResult:
    """引言解析结果。"""

    lines: list[QuoteLine]
    pure_center: bool


@dataclass
class CardPayload:
    """渲染层需要的完整卡片载荷。"""

    title: str
    artist: str
    cover_url: str
    quote_content: str
    quote_source: str
    date_obj: datetime
    music_id: Optional[str]
    song_url: Optional[str] = None
    progress_ms: Optional[int] = None
    duration_ms: Optional[int] = None


@dataclass
class LayoutMetrics:
    """布局测量结果，用于后续绘制阶段。"""

    text_w: float
    t_lines: list[str]
    a_lines: list[str]
    t_h: int
    a_h: int
    header_h_real: float
    header_section_h: float
    middle_h: float
    footer_inner_h: float
    q_x: float
    q_max_w: float
    total_card_h: float
    total_img_h: int
    cover_size: int
    qr_size: int
