import argparse
import asyncio
import calendar
import json
import logging
import re
import sys
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from functools import lru_cache
from io import BytesIO
from typing import Any, Dict, Optional, Protocol, Union

import aiohttp
import emoji
import qrcode
from PIL import Image, ImageDraw, ImageEnhance, ImageFilter, ImageFont, ImageOps

from ttml.ttml import TTML

TTML_DB_URL_PREFIX = "https://amlldb.bikonoo.com"
AMLL_BASE_URL = "https://amlldb.bikonoo.com"

logger = logging.getLogger(__name__)

DEFAULT_USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/142.0.0.0 Safari/537.36 Edg/142.0.0.0"
)


class Platform(str, Enum):
    NCM = "ncm"
    QQ = "qq"
    AM = "am"


class Mode(str, Enum):
    DAILY = "daily"
    CARD = "card"
    LYRIC = "lyric"


@dataclass
class SongInfo:
    title: str
    artist: str
    cover_url: str
    music_id: str
    song_url: Optional[str] = None


@dataclass
class QuoteData:
    content: str
    source: str


@dataclass
class CardStyle:
    main: str = "#2A2A2A"
    sub: str = "#555555"
    quote: str = "#4A4A4A"
    accent: str = "#D0D0D0"
    footer_center: str = "#555555"
    watermark_designed: str = "Designed by HamuChan"
    watermark_generated: str = "Generated by KhBot v1.6.2"


@dataclass
class CardLayout:
    width: int = 1000
    margin_top: int = 40
    margin_side: int = 40
    margin_bottom: int = 90
    inner_pad: int = 40

    @property
    def card_width(self) -> int:
        return self.width - (self.margin_side * 2)

    @property
    def content_left_x(self) -> int:
        return self.margin_side + self.inner_pad

    @property
    def content_right_x(self) -> int:
        return self.margin_side + self.card_width - self.inner_pad

    @property
    def max_text_width(self) -> int:
        return self.card_width - (self.inner_pad * 2)


@dataclass
class CardRequest:
    platform: Platform = Platform.NCM
    mode: Mode = Mode.DAILY
    date_str: str = field(default_factory=lambda: datetime.now().strftime("%Y-%m-%d"))
    music_id: Optional[str] = None
    song_info: Optional[SongInfo] = None
    quote: Optional[QuoteData] = None
    inner_blurred: bool = False
    show_qrcode: bool = False
    font_path: str = "PingFang.ttc"
    am_storefront: str = "cn"
    style: CardStyle = field(default_factory=CardStyle)
    layout: CardLayout = field(default_factory=CardLayout)


@dataclass
class CardResult:
    success: bool
    image: Optional[Image.Image] = None
    music_id: Optional[str] = None
    error_code: Optional[str] = None
    message: str = ""


@dataclass
class DailyRecommendation:
    music_id: Optional[str]
    date: Optional[str]
    username: Optional[str]
    comment: Optional[str]
    cover_path: Optional[str]


@dataclass
class QuoteLine:
    spec: Optional[str]
    text: str


@dataclass
class QuoteParseResult:
    lines: list[QuoteLine]
    pure_center: bool


@dataclass
class CardPayload:
    title: str
    artist: str
    cover_url: str
    quote_content: str
    quote_source: str
    date_obj: datetime
    music_id: Optional[str]
    song_url: Optional[str] = None


@dataclass
class LayoutMetrics:
    text_w: float
    t_lines: list[str]
    a_lines: list[str]
    t_h: int
    a_h: int
    header_h_real: float
    header_section_h: float
    middle_h: float
    footer_inner_h: float
    q_x: float
    q_max_w: float
    total_card_h: float
    total_img_h: int
    cover_size: int
    qr_size: int


class HttpClient:
    def __init__(
        self,
        headers: Optional[Dict[str, str]] = None,
        timeout: int = 10,
        trust_env: bool = False,
    ):
        self._headers = headers or {}
        self._timeout = aiohttp.ClientTimeout(total=timeout)
        self._trust_env = trust_env
        self._session: Optional[aiohttp.ClientSession] = None

    async def __aenter__(self) -> "HttpClient":
        await self._ensure_session()
        return self

    async def __aexit__(self, exc_type, exc, tb) -> None:
        await self.close()

    async def _ensure_session(self) -> aiohttp.ClientSession:
        if self._session is None or self._session.closed:
            self._session = aiohttp.ClientSession(
                headers=self._headers,
                timeout=self._timeout,
                trust_env=self._trust_env,
            )
        return self._session

    async def close(self) -> None:
        if self._session and not self._session.closed:
            await self._session.close()

    async def get_text(self, url: str, **kwargs: Any) -> tuple[int, str]:
        session = await self._ensure_session()
        try:
            async with session.get(url, **kwargs) as resp:
                return resp.status, await resp.text()
        except Exception as exc:
            logger.error("HTTP GET text failed: %s", exc)
            return 0, ""

    async def get_bytes(self, url: str, **kwargs: Any) -> tuple[int, bytes]:
        session = await self._ensure_session()
        try:
            async with session.get(url, **kwargs) as resp:
                return resp.status, await resp.read()
        except Exception as exc:
            logger.error("HTTP GET bytes failed: %s", exc)
            return 0, b""

    async def get_json(self, url: str, **kwargs: Any) -> tuple[int, Any]:
        status, text = await self.get_text(url, **kwargs)
        if status != 200 or not text:
            return status, None
        try:
            return status, json.loads(text)
        except json.JSONDecodeError as exc:
            logger.error("JSON decode failed for GET %s: %s", url, exc)
            return status, None

    async def post_json(self, url: str, payload: Dict[str, Any], **kwargs: Any) -> tuple[int, Any]:
        session = await self._ensure_session()
        try:
            async with session.post(url, json=payload, **kwargs) as resp:
                text = await resp.text()
                if resp.status != 200 or not text:
                    return resp.status, None
                return resp.status, json.loads(text)
        except Exception as exc:
            logger.error("HTTP POST json failed: %s", exc)
            return 0, None

    async def resolve_final_url(
        self,
        url: str,
        max_redirects: int = 10,
    ) -> Optional[str]:
        session = await self._ensure_session()
        try:
            async with session.get(
                url,
                allow_redirects=True,
                max_redirects=max_redirects,
            ) as response:
                return str(response.url)
        except Exception as exc:
            logger.error("resolve_final_url failed: %s", exc)
            return None


class SongInfoProvider(Protocol):
    async def fetch_song(self, music_id: str, http_client: HttpClient) -> Optional[SongInfo]:
        raise NotImplementedError

    def build_song_url(self, music_id: str, storefront: str = "cn") -> str:
        raise NotImplementedError


class NcmProvider:
    async def fetch_song(self, music_id: str, http_client: HttpClient) -> Optional[SongInfo]:
        url = f"https://music.163.com/api/song/detail/?id={music_id}&ids=%5B{music_id}%5D"
        headers = {
            "User-Agent": DEFAULT_USER_AGENT,
        }
        logger.info("正在从 NCM API 获取 ID %s 的信息...", music_id)
        status, data = await http_client.get_json(url, headers=headers)
        if status != 200 or not data or not data.get("songs"):
            return None

        try:
            song = data["songs"][0]
            return SongInfo(
                title=song["name"],
                artist=" / ".join([a["name"] for a in song["artists"]]),
                cover_url=song["album"]["picUrl"],
                music_id=str(music_id),
            )
        except (KeyError, TypeError, IndexError) as exc:
            logger.error("NCM payload parse error: %s", exc)
            return None

    def build_song_url(self, music_id: str, storefront: str = "cn") -> str:
        _ = storefront
        return f"https://music.163.com/#/song?id={music_id}"

class QqProvider:
    _ID_PATTERN = re.compile(r"^[0-9a-zA-Z]+$")
    _SHORT_LINK_PATTERN = re.compile(r"u\?__=[0-9a-zA-Z]")
    _EXTRACT_PATTERN = re.compile(r"(songDetail/|songmid=)([0-9a-zA-Z]+)")

    async def normalize_music_id(self, raw_music_id: str, http_client: HttpClient) -> Optional[str]:
        if self._ID_PATTERN.match(raw_music_id):
            return raw_music_id

        music_id = raw_music_id
        if self._SHORT_LINK_PATTERN.findall(raw_music_id):
            resolved = await http_client.resolve_final_url(raw_music_id)
            if resolved is None:
                return None
            music_id = resolved

        match = self._EXTRACT_PATTERN.search(music_id)
        if not match:
            return None
        return match.group(2)

    async def fetch_song(self, music_id: str, http_client: HttpClient) -> Optional[SongInfo]:
        normalized_id = await self.normalize_music_id(music_id, http_client)
        if not normalized_id:
            return None

        logger.info("正在访问 QQ 音乐网页端获取 ID %s 的信息...", normalized_id)
        req_body: Dict[str, Any] = {
            "comm": {
                "ct": "26",
                "cv": "2010101",
                "v": "2010101",
            },
            "req": {
                "module": "music.trackInfo.UniformRuleCtrl",
                "method": "CgiGetTrackInfo",
                "param": {
                    "types": [1],
                    "ctx": 0,
                },
            },
        }

        if normalized_id.startswith("00"):
            req_body["req"]["param"]["mids"] = [str(normalized_id)]
        else:
            try:
                req_body["req"]["param"]["ids"] = [int(normalized_id)]
            except ValueError:
                return None

        status, data = await http_client.post_json("https://u.y.qq.com/cgi-bin/musicu.fcg", req_body)
        if status != 200 or not data or not data.get("req"):
            return None

        try:
            song = data["req"]["data"]["tracks"][0]
            title = song["title"]
            subtitle = song.get("subtitle")
            if subtitle and len(subtitle):
                title = f"{title} ({subtitle})"

            return SongInfo(
                title=title,
                artist=" / ".join([singer["name"] for singer in song["singer"]]),
                cover_url=f"https://y.qq.com/music/photo_new/T002R1200x1200M000{song['album']['mid']}.jpg",
                music_id=str(normalized_id),
            )
        except (KeyError, TypeError, IndexError) as exc:
            logger.error("QQ payload parse error: %s", exc)
            return None

    def build_song_url(self, music_id: str, storefront: str = "cn") -> str:
        _ = storefront
        return f"https://y.qq.com/n/ryqq_v2/songDetail/{music_id}"


class AppleProvider:
    def __init__(self, country: str = "cn"):
        self.country = country

    async def fetch_song(self, music_id: str, http_client: HttpClient) -> Optional[SongInfo]:
        _ = http_client
        try:
            from curl_cffi.requests import AsyncSession
        except ImportError:
            logger.error("请先安装 curl_cffi 以使用 Apple Music 功能: pip install curl_cffi")
            return None

        logger.info("正在从 Apple Music API 获取 ID %s 的信息...", music_id)
        base_url = "https://itunes.apple.com/lookup"
        params = {
            "id": music_id,
            "entity": "song",
            "country": self.country,
            "limit": 1,
        }

        try:
            async with AsyncSession(impersonate="chrome120") as session:
                response = await session.get(base_url, params=params)
                if response.status_code != 200:
                    logger.error("AM API Error: %s", response.status_code)
                    return None

                data = response.json()
                if data.get("resultCount", 0) <= 0:
                    logger.warning("未找到歌曲 ID: %s", music_id)
                    return None

                song_data = data["results"][0]
                cover_url = song_data.get("artworkUrl100", "")
                if cover_url:
                    cover_url = cover_url.replace("100x100bb", "1024x1024bb")

                return SongInfo(
                    title=song_data.get("trackName", ""),
                    artist=song_data.get("artistName", ""),
                    cover_url=cover_url,
                    music_id=str(song_data.get("trackId", music_id)),
                    song_url=song_data.get("trackViewUrl"),
                )
        except Exception as exc:
            logger.error("AM API Error: %s", exc)
            return None

    def build_song_url(self, music_id: str, storefront: str = "cn") -> str:
        return f"https://music.apple.com/{storefront}/song/{music_id}"


class DailyRecommendationService:
    async def fetch(self, date_str: str, http_client: HttpClient) -> Optional[DailyRecommendation]:
        logger.info("正在获取 %s 的每日推荐...", date_str)
        url = f"{AMLL_BASE_URL}/api/daily-recommendations?date={date_str}"
        status, text = await http_client.get_text(url)
        if status != 200:
            logger.warning("Daily recommendation request failed: %s", status)
            return None

        if not text or text.strip() == "null":
            logger.info("该日期无每日推荐数据")
            return None

        try:
            data = json.loads(text)
        except json.JSONDecodeError as exc:
            logger.error("Daily recommendation JSON decode error: %s", exc)
            return None

        if not isinstance(data, dict) or "ncm_id" not in data:
            return None

        return DailyRecommendation(
            music_id=data.get("ncm_id"),
            date=data.get("date"),
            username=data.get("username"),
            comment=data.get("comment"),
            cover_path=data.get("cover"),
        )


class LyricsService:
    _FOLDER_MAP: Dict[Platform, str] = {
        Platform.NCM: "ncm-lyrics",
        Platform.QQ: "qq-lyrics",
        Platform.AM: "am-lyrics",
    }

    async def fetch(self, music_id: str, platform: Platform, http_client: HttpClient) -> Optional[str]:
        folder = self._FOLDER_MAP.get(platform)
        if not folder:
            logger.warning("目前不支持平台 %s 的歌词获取", platform.value)
            return None

        url = f"{TTML_DB_URL_PREFIX}/{folder}/{music_id}.ttml"
        logger.info("正在从 %s 获取 %s 的 TTML 文件...", url, music_id)
        status, text = await http_client.get_text(url)
        if status != 200:
            logger.warning("TTML fetch failed: %s", status)
            return None

        if not text or text.strip() == "null":
            logger.info("该 ID 所对应歌词还无人制作")
            return None

        try:
            return TTML(text).text
        except Exception as exc:
            logger.error("TTML parse failed: %s", exc)
            return None


class QuoteParser:
    _PATTERN = re.compile(r"^\[([:_-]+)\](.*)")

    @classmethod
    def parse(cls, raw_text: str) -> QuoteParseResult:
        normalized = clean_emojis(from_html_escaped(raw_text))
        lines: list[QuoteLine] = []
        pure_center = True

        for line in normalized.split("\n"):
            stripped = line.strip()
            match = cls._PATTERN.match(stripped)
            if match:
                spec, text_content = match.groups()
                text_content = text_content.strip()
                lines.append(QuoteLine(spec=spec, text=text_content))
                if spec != "-":
                    pure_center &= spec == ":-:" or spec == ":_:"
            else:
                lines.append(QuoteLine(spec=None, text=stripped))

        return QuoteParseResult(lines=lines, pure_center=pure_center)


def _coerce_platform(value: Union[str, Platform]) -> Platform:
    if isinstance(value, Platform):
        return value
    try:
        return Platform(value)
    except ValueError:
        logger.warning("未知平台 %s，回退到 ncm", value)
        return Platform.NCM


def _coerce_mode(value: Union[str, Mode]) -> Mode:
    if isinstance(value, Mode):
        return value
    try:
        return Mode(value)
    except ValueError:
        logger.warning("未知模式 %s，回退到 daily", value)
        return Mode.DAILY


def get_song_provider(platform: Platform, am_storefront: str = "cn") -> SongInfoProvider:
    if platform == Platform.NCM:
        return NcmProvider()
    if platform == Platform.QQ:
        return QqProvider()
    if platform == Platform.AM:
        return AppleProvider(am_storefront)
    return NcmProvider()


async def download_image_with_fallback(url: str, http_client: HttpClient) -> Image.Image:
    if not url:
        return Image.new("RGB", (600, 600), color="#D3D3D3")

    status, content = await http_client.get_bytes(url)
    if status == 200 and content:
        try:
            return Image.open(BytesIO(content))
        except Exception as exc:
            logger.warning("图片解码失败，尝试 fallback: %s", exc)

    logger.warning("图片下载失败: %s，尝试使用 TLS 指纹...", status)
    try:
        from curl_cffi import requests

        response = requests.get(url, impersonate="chrome110")
        return Image.open(BytesIO(response.content))
    except Exception as exc:
        logger.error("图片下载出错: %s", exc)
        return Image.new("RGB", (600, 600), color="#D3D3D3")

class MusicCard:
    DAILY = Mode.DAILY.value
    CARD = Mode.CARD.value
    LYRIC = Mode.LYRIC.value

    Regular = 2
    Medium = 5
    Semibold = 8
    Light = 11
    Thin = 14
    Ultralight = 17

    def __init__(
        self,
        font_path: str,
        platform: Union[str, Platform] = Platform.NCM,
        am_storefront: str = "cn",
        style: Optional[CardStyle] = None,
        layout: Optional[CardLayout] = None,
    ):
        self.font_path = font_path
        self.platform = _coerce_platform(platform)
        self.am_storefront = am_storefront
        self.style = style or CardStyle()
        self.layout = layout or CardLayout()

        self.W = self.layout.width
        self.MARGIN_TOP = self.layout.margin_top
        self.MARGIN_SIDE = self.layout.margin_side
        self.MARGIN_BOTTOM = self.layout.margin_bottom
        self.CARD_W = self.layout.card_width
        self.INNER_PAD = self.layout.inner_pad
        self.CONTENT_LEFT_X = self.layout.content_left_x
        self.CONTENT_RIGHT_X = self.layout.content_right_x
        self.MAX_TEXT_W = self.layout.max_text_width

        self.C_MAIN = self.style.main
        self.C_SUB = self.style.sub
        self.C_QUOTE = self.style.quote
        self.C_ACCENT = self.style.accent
        self.C_FOOTER_CENTER = self.style.footer_center

    @staticmethod
    async def download_image(url: str) -> Image.Image:
        headers = {"User-Agent": DEFAULT_USER_AGENT}
        async with HttpClient(headers=headers, timeout=10, trust_env=True) as http_client:
            return await download_image_with_fallback(url, http_client)

    @staticmethod
    async def fetch_ncm_song_info(music_id: str) -> Optional[Dict[str, Any]]:
        async with HttpClient(timeout=15, trust_env=True) as http_client:
            song = await NcmProvider().fetch_song(music_id, http_client)
            return _song_info_to_dict(song)

    @staticmethod
    async def get_final_url(
        url: str,
        max_redirects: int = 10,
        timeout: int = 30,
    ) -> Optional[str]:
        async with HttpClient(timeout=timeout, trust_env=True) as http_client:
            return await http_client.resolve_final_url(url, max_redirects=max_redirects)

    @staticmethod
    async def fetch_qq_music_info(music_id: str) -> Optional[Dict[str, Any]]:
        async with HttpClient(timeout=15, trust_env=True) as http_client:
            song = await QqProvider().fetch_song(music_id, http_client)
            return _song_info_to_dict(song)

    @staticmethod
    async def fetch_apple_music_info(music_id: str, country: str = "cn") -> Optional[Dict[str, Any]]:
        async with HttpClient(timeout=15, trust_env=True) as http_client:
            song = await AppleProvider(country).fetch_song(music_id, http_client)
            return _song_info_to_dict(song)

    @staticmethod
    async def fetch_daily_recommendation(date_str: str) -> Optional[Dict[str, Any]]:
        async with HttpClient(timeout=10, trust_env=True) as http_client:
            rec = await DailyRecommendationService().fetch(date_str, http_client)
            if not rec:
                return None
            return {
                "music_id": rec.music_id,
                "date": rec.date,
                "username": rec.username,
                "comment": rec.comment,
                "cover_path": rec.cover_path,
            }

    @staticmethod
    def get_dominant_color(image: Image.Image) -> tuple[int, int, int]:
        return image.copy().resize((1, 1), resample=Image.Resampling.HAMMING).getpixel((0, 0))

    @staticmethod
    def get_adaptive_month_color(bg_sample: Image.Image, theme_rgb: tuple[int, int, int]) -> tuple[int, int, int]:
        bg_color = bg_sample.resize((1, 1), resample=Image.Resampling.HAMMING).getpixel((0, 0))
        bg_lum = (bg_color[0] * 299 + bg_color[1] * 587 + bg_color[2] * 114) / 1000

        def adjust(color: tuple[int, int, int], factor: float) -> tuple[int, int, int]:
            return tuple(min(255, max(0, int(i * factor))) for i in color)

        return adjust(theme_rgb, 0.6) if bg_lum > 140 else adjust(theme_rgb, 1.8)

    @staticmethod
    def get_adaptive_deco_color(bg_sample: Image.Image, theme_rgb: tuple[int, int, int]) -> tuple[int, int, int]:
        bg_color = bg_sample.resize((1, 1), resample=Image.Resampling.HAMMING).getpixel((0, 0))
        bg_lum = (bg_color[0] * 299 + bg_color[1] * 587 + bg_color[2] * 114) / 1000

        def blend(c1: tuple[int, int, int], c2: tuple[int, int, int], ratio: float) -> tuple[int, int, int]:
            return tuple(int(c1[i] * (1 - ratio) + c2[i] * ratio) for i in range(3))

        white = (255, 255, 255)
        return blend(theme_rgb, white, 0.2) if bg_lum > 150 else blend(theme_rgb, white, 0.6)

    @staticmethod
    def get_contrasting_text_color(region_image: Image.Image) -> str:
        color = region_image.resize((1, 1), resample=Image.Resampling.HAMMING).getpixel((0, 0))
        lum = (color[0] * 299 + color[1] * 587 + color[2] * 114) / 1000
        return "#4a3b32" if lum > 120 else "#f2f2f2"

    @staticmethod
    def _get_relative_luminance(rgb: tuple[int, int, int]) -> float:
        r, g, b = [x / 255.0 for x in rgb]
        r = r / 12.92 if r <= 0.03928 else ((r + 0.055) / 1.055) ** 2.4
        g = g / 12.92 if g <= 0.03928 else ((g + 0.055) / 1.055) ** 2.4
        b = b / 12.92 if b <= 0.03928 else ((b + 0.055) / 1.055) ** 2.4
        return 0.2126 * r + 0.7152 * g + 0.0722 * b

    @classmethod
    def _get_contrast_ratio(cls, rgb1: tuple[int, int, int], rgb2: tuple[int, int, int]) -> float:
        lum1 = cls._get_relative_luminance(rgb1)
        lum2 = cls._get_relative_luminance(rgb2)
        if lum1 > lum2:
            return (lum1 + 0.05) / (lum2 + 0.05)
        return (lum2 + 0.05) / (lum1 + 0.05)

    @classmethod
    def get_safe_qr_color(
        cls,
        theme_rgb: tuple[int, int, int],
        bg_color_rgb: tuple[int, int, int] = (253, 253, 253),
    ) -> tuple[int, int, int]:
        min_contrast_ratio = 4.5
        current_color = list(theme_rgb)

        while cls._get_contrast_ratio(tuple(current_color), bg_color_rgb) < min_contrast_ratio:
            if current_color[0] <= 5 and current_color[1] <= 5 and current_color[2] <= 5:
                return 0, 0, 0
            current_color[0] = max(0, int(current_color[0] * 0.9))
            current_color[1] = max(0, int(current_color[1] * 0.9))
            current_color[2] = max(0, int(current_color[2] * 0.9))

        return tuple(current_color)

    @staticmethod
    def generate_styled_qrcode(data: str, theme_color: tuple[int, int, int], size: int = 120) -> Image.Image:
        qr = qrcode.QRCode(version=1, border=1, box_size=10)
        qr.add_data(data)
        qr.make(fit=True)
        qr_img = qr.make_image(fill_color="black", back_color="white").convert("RGBA")

        new_data = []
        tr, tg, tb = theme_color
        for item in qr_img.getdata():
            if item[0] < 128:
                new_data.append((tr, tg, tb, 230))
            else:
                new_data.append((255, 255, 255, 0))

        qr_img.putdata(new_data)
        return qr_img.resize((size, size), Image.Resampling.LANCZOS)

    @staticmethod
    def create_gradient_mask(w: int, h: int) -> Image.Image:
        ending = 0.9
        limit = 255 * ending
        break_percent = 0.5
        break_opa = limit * break_percent
        break_h = min(1100, h * break_percent * ending)
        exponent = 1.5

        data: list[int] = []
        for y in range(h):
            if y < break_h:
                val = int(break_opa * (y / break_h)) if break_h > 0 else 0
            else:
                denom = h - break_h
                ratio = (y - break_h) / denom if denom > 0 else 1
                ratio = ratio ** exponent
                val = int(break_opa + (limit - break_opa) * ratio)
            data.append(val)

        gradient = Image.new("L", (1, h))
        gradient.putdata(data)
        return gradient.resize((w, h))

    @staticmethod
    def create_rounded_mask(size: tuple[int, int], radius: int) -> Image.Image:
        upscale_factor = 8
        scaled_size = (size[0] * upscale_factor, size[1] * upscale_factor)
        scaled_radius = radius * upscale_factor

        mask = Image.new("L", scaled_size, 0)
        draw = ImageDraw.Draw(mask)
        draw.rounded_rectangle((0, 0) + scaled_size, radius=scaled_radius, fill=255)
        return mask.resize(size, Image.Resampling.LANCZOS)

    @staticmethod
    def contains_cjk(text: str) -> bool:
        for char in text:
            if "\u4e00" <= char <= "\u9fff":
                return True
        return False

    def _process_text_wrapping(
        self,
        draw: ImageDraw.ImageDraw,
        text: str,
        font: ImageFont.FreeTypeFont,
        max_width: float,
    ) -> tuple[list[str], int]:
        final_lines: list[str] = []
        bbox = font.getbbox("高")
        line_height = bbox[3] - bbox[1]

        for paragraph in text.split("\n"):
            paragraph = paragraph.strip()
            if not paragraph:
                final_lines.append("")
                continue

            if self.contains_cjk(paragraph):
                current_line = ""
                for char in paragraph:
                    if draw.textlength(current_line + char, font=font) <= max_width:
                        current_line += char
                    else:
                        if " " in current_line:
                            final_lines.append(current_line[: current_line.rindex(" ")])
                            current_line = current_line[current_line.rindex(" ") + 1 :]
                            current_line += char
                        else:
                            final_lines.append(current_line)
                            current_line = char
                if current_line:
                    final_lines.append(current_line)
            else:
                words = paragraph.split(" ")
                current_line = ""
                for word in words:
                    word_width = draw.textlength(word, font=font)
                    if word_width > max_width:
                        if current_line:
                            final_lines.append(current_line)
                            current_line = ""

                        hyphen_width = draw.textlength("-", font=font)
                        effective_max_width = max_width - hyphen_width
                        temp_chunk = ""
                        for char in word:
                            if draw.textlength(temp_chunk + char, font=font) <= effective_max_width:
                                temp_chunk += char
                            else:
                                final_lines.append(temp_chunk + "-")
                                temp_chunk = char
                        if temp_chunk:
                            current_line = temp_chunk
                        continue

                    separator = " " if current_line else ""
                    test_line = current_line + separator + word
                    if draw.textlength(test_line, font=font) <= max_width:
                        current_line = test_line
                    else:
                        final_lines.append(current_line)
                        current_line = word

                if current_line:
                    final_lines.append(current_line)

        return final_lines, line_height

    @staticmethod
    def _draw_text_right(
        draw: ImageDraw.ImageDraw,
        text: str,
        font: ImageFont.FreeTypeFont,
        right_x: float,
        y: float,
        fill: str,
    ) -> None:
        w = draw.textlength(text, font=font)
        draw.text((right_x - w, y), text, font=font, fill=fill)

    @staticmethod
    @lru_cache(maxsize=256)
    def _cached_font(font_path: str, size: int, index: int) -> ImageFont.FreeTypeFont:
        return ImageFont.truetype(font_path, size, index=index)

    def _load_font(self, size: int, index: int) -> ImageFont.FreeTypeFont:
        return self._cached_font(self.font_path, size, index)

    def _prepare_fonts(self) -> Dict[str, ImageFont.FreeTypeFont]:
        return {
            "title": self._load_font(44, self.Semibold),
            "artist": self._load_font(26, self.Semibold),
            "date_num": self._load_font(90, self.Medium),
            "date_month": self._load_font(40, self.Medium),
            "quote": self._load_font(34, self.Regular),
            "quote_sub": self._load_font(26, self.Light),
            "deco": self._load_font(100, self.Medium),
            "footer_center": self._load_font(32, self.Thin),
            "footer_outer": self._load_font(22, self.Regular),
        }

    def _measure_quote_height(
        self,
        draw: ImageDraw.ImageDraw,
        quote_parse: QuoteParseResult,
        q_max_w: float,
        font_quote: ImageFont.FreeTypeFont,
        font_quote_small: ImageFont.FreeTypeFont,
    ) -> float:
        q_h_real = 0.0
        q_font_h = font_quote.getbbox("高")[3] - font_quote.getbbox("高")[1]
        small_q_font_h = (
            font_quote_small.getbbox("高")[3] - font_quote_small.getbbox("高")[1]
        )

        for quote_line in quote_parse.lines:
            spec = quote_line.spec
            text_content = quote_line.text

            if spec:
                if spec == "-":
                    if not text_content.strip():
                        q_h_real += q_font_h * 0.25
                    else:
                        q_h_real += q_font_h * 0.5 + q_font_h / 1.5
                else:
                    use_small_font = "_" in spec
                    target_font = font_quote_small if use_small_font else font_quote
                    target_font_h = small_q_font_h if use_small_font else q_font_h
                    wrap_width = q_max_w * (1 if quote_parse.pure_center else 0.8)
                    wrapped_sub_lines, _ = self._process_text_wrapping(
                        draw,
                        text_content.strip(),
                        target_font,
                        wrap_width,
                    )
                    q_h_real += len(wrapped_sub_lines) * target_font_h * 1.6
            else:
                if not text_content.strip():
                    q_h_real += q_font_h * 1.6
                    continue
                wrapped_sub_lines, _ = self._process_text_wrapping(draw, text_content, font_quote, q_max_w)
                q_h_real += len(wrapped_sub_lines) * q_font_h * 1.6

        return q_h_real

    def measure_layout(
        self,
        payload: CardPayload,
        mode: Mode,
        fonts: Dict[str, ImageFont.FreeTypeFont],
        quote_parse: QuoteParseResult,
        show_qrcode: bool,
    ) -> LayoutMetrics:
        qr_size = 120
        qr_gap = 20

        text_w = self.MAX_TEXT_W
        if show_qrcode and payload.music_id:
            text_w -= qr_size + qr_gap

        temp_draw = ImageDraw.Draw(Image.new("RGB", (1, 1)))
        t_lines, t_h = self._process_text_wrapping(temp_draw, payload.title, fonts["title"], text_w)
        a_lines, a_h = self._process_text_wrapping(temp_draw, payload.artist, fonts["artist"], text_w)

        text_block_h = (len(t_lines) * t_h * 1.3) + 15 + (len(a_lines) * a_h * 1.5)
        header_h_real = max(text_block_h, qr_size) if (show_qrcode and payload.music_id) else text_block_h

        q_max_w = 0.0
        q_x = 0.0
        footer_inner_h = 0.0
        header_section_h = 0.0
        middle_h = 0.0

        if mode == Mode.CARD:
            header_section_h = header_h_real
            middle_h = 0
            footer_inner_h = 60
        else:
            header_section_h = header_h_real + 30 + 4 + 40
            q_x = self.CONTENT_LEFT_X + (240 if mode == Mode.DAILY else 0)
            q_max_w = self.CONTENT_RIGHT_X - q_x

            font_quote_small = self._load_font(int(fonts["quote"].size * 0.8), self.Regular)
            q_h_real = self._measure_quote_height(
                temp_draw,
                quote_parse,
                q_max_w,
                fonts["quote"],
                font_quote_small,
            )

            if mode == Mode.DAILY:
                q_h = q_h_real + 40 + 30
                footer_inner_h = 20 + 20 + 32 + 25
            else:
                q_h = q_h_real + 30
                footer_inner_h = 0

            middle_h = max(200, q_h)

        cover_size = self.MAX_TEXT_W
        total_card_h = self.INNER_PAD + cover_size + header_section_h + footer_inner_h
        if mode != Mode.CARD:
            total_card_h += 30 + middle_h
        total_img_h = int(total_card_h + self.MARGIN_TOP + self.MARGIN_BOTTOM)

        return LayoutMetrics(
            text_w=text_w,
            t_lines=t_lines,
            a_lines=a_lines,
            t_h=t_h,
            a_h=a_h,
            header_h_real=header_h_real,
            header_section_h=header_section_h,
            middle_h=middle_h,
            footer_inner_h=footer_inner_h,
            q_x=q_x,
            q_max_w=q_max_w,
            total_card_h=total_card_h,
            total_img_h=total_img_h,
            cover_size=cover_size,
            qr_size=qr_size,
        )

    def render_background(
        self,
        cover_img_raw: Image.Image,
        metrics: LayoutMetrics,
        inner_blurred: bool,
    ) -> tuple[Image.Image, ImageDraw.ImageDraw]:
        bg_img = ImageOps.fit(
            cover_img_raw,
            (self.W, metrics.total_img_h),
            method=Image.Resampling.LANCZOS,
        )
        bg_img = bg_img.filter(ImageFilter.GaussianBlur(radius=100))
        bg_img = ImageEnhance.Brightness(bg_img).enhance(0.7)

        if inner_blurred:
            card_crop = bg_img.crop(
                (
                    self.MARGIN_SIDE,
                    self.MARGIN_TOP,
                    self.MARGIN_SIDE + self.CARD_W,
                    self.MARGIN_TOP + metrics.total_card_h,
                )
            )
            card_crop = ImageEnhance.Brightness(card_crop).enhance(1.2)
            white_layer = Image.new("RGB", card_crop.size, "#FDFDFD")
            mask = self.create_gradient_mask(card_crop.width, card_crop.height)
            card_bg = Image.composite(white_layer, card_crop, mask)
        else:
            card_bg = Image.new("RGB", (self.CARD_W, int(metrics.total_card_h)), "#FDFDFD")

        card_mask = self.create_rounded_mask(card_bg.size, 40)
        bg_img.paste(card_bg, (self.MARGIN_SIDE, self.MARGIN_TOP), card_mask)

        cover_resized = ImageOps.fit(
            cover_img_raw,
            (metrics.cover_size, metrics.cover_size),
            method=Image.Resampling.LANCZOS,
        )
        bg_img.paste(
            cover_resized,
            (self.CONTENT_LEFT_X, self.MARGIN_TOP + self.INNER_PAD),
            self.create_rounded_mask(cover_resized.size, 30),
        )

        return bg_img, ImageDraw.Draw(bg_img)

    def _build_song_url(self, payload: CardPayload) -> str:
        if payload.song_url:
            return payload.song_url
        if not payload.music_id:
            return ""
        provider = get_song_provider(self.platform, self.am_storefront)
        return provider.build_song_url(payload.music_id, storefront=self.am_storefront)

    def render_header(
        self,
        draw: ImageDraw.ImageDraw,
        bg_img: Image.Image,
        payload: CardPayload,
        metrics: LayoutMetrics,
        fonts: Dict[str, ImageFont.FreeTypeFont],
        show_qrcode: bool,
        theme_rgb: tuple[int, int, int],
    ) -> float:
        cursor_y = self.MARGIN_TOP + self.INNER_PAD + metrics.cover_size + 30
        header_start_y = cursor_y

        for line in metrics.t_lines:
            draw.text((self.CONTENT_LEFT_X, cursor_y), line, font=fonts["title"], fill=self.C_MAIN)
            cursor_y += metrics.t_h * 1.3
        cursor_y += 15

        for line in metrics.a_lines:
            draw.text((self.CONTENT_LEFT_X, cursor_y), line, font=fonts["artist"], fill=self.C_SUB)
            cursor_y += metrics.a_h * 1.5

        if show_qrcode and payload.music_id:
            song_url = self._build_song_url(payload)
            qr_x = int(self.CONTENT_RIGHT_X - metrics.qr_size)
            qr_y = int(header_start_y)
            qr_region_box = (qr_x, qr_y, qr_x + metrics.qr_size, qr_y + metrics.qr_size)
            qr_background_sample = bg_img.crop(qr_region_box)
            avg_bg_color = self.get_dominant_color(qr_background_sample)
            safe_qr_color = self.get_safe_qr_color(theme_rgb, avg_bg_color)
            qr_img = self.generate_styled_qrcode(song_url, safe_qr_color, size=metrics.qr_size)
            bg_img.paste(qr_img, (qr_x, qr_y), qr_img)

        return header_start_y

    def _draw_dot_line(self, draw: ImageDraw.ImageDraw, y: float) -> None:
        for x in range(self.CONTENT_LEFT_X, self.CONTENT_RIGHT_X, 20):
            draw.ellipse((x, y, x + 4, y + 4), fill=self.C_ACCENT)

    def render_quote(
        self,
        draw: ImageDraw.ImageDraw,
        bg_img: Image.Image,
        payload: CardPayload,
        metrics: LayoutMetrics,
        fonts: Dict[str, ImageFont.FreeTypeFont],
        quote_parse: QuoteParseResult,
        mode: Mode,
        theme_rgb: tuple[int, int, int],
        header_start_y: float,
    ) -> float:
        sep_y = header_start_y + metrics.header_h_real
        if mode == Mode.CARD:
            return sep_y

        sep_y = header_start_y + metrics.header_h_real + 30
        self._draw_dot_line(draw, sep_y)
        mid_y = sep_y + 40

        date_month_str = calendar.month_abbr[payload.date_obj.month]
        date_day_int = payload.date_obj.day

        if mode == Mode.DAILY:
            date_x = self.CONTENT_LEFT_X + 20
            month_color = self.get_adaptive_month_color(
                bg_img.crop((date_x, mid_y, date_x + 80, mid_y + 40)),
                theme_rgb,
            )
            draw.text((date_x, mid_y), date_month_str, font=fonts["date_month"], fill=month_color)
            m_bbox = fonts["date_month"].getbbox("A")
            draw.text(
                (date_x, mid_y + (m_bbox[3] - m_bbox[1]) + 10),
                str(date_day_int),
                font=fonts["date_num"],
                fill=self.C_MAIN,
            )

        deco_x = self.CONTENT_RIGHT_X - 80
        deco_y = metrics.total_img_h - 260 if mode == Mode.DAILY else metrics.total_img_h - 180
        deco_color = self.get_adaptive_deco_color(
            bg_img.crop((int(deco_x), int(deco_y), int(deco_x + 60), int(deco_y + 60))),
            theme_rgb,
        )
        draw.text((deco_x, deco_y), "”", font=fonts["deco"], fill=deco_color)

        q_curr_y = mid_y + 5
        q_font_h = fonts["quote"].getbbox("高")[3] - fonts["quote"].getbbox("高")[1]

        for quote_line in quote_parse.lines:
            spec = quote_line.spec
            text_content = quote_line.text

            if spec:
                if spec == "-":
                    padding_v = q_font_h * 0.25
                    if not text_content:
                        q_curr_y += padding_v
                    else:
                        div_font_size = max(8, int(fonts["quote"].size / 1.5))
                        div_font = self._load_font(div_font_size, self.Regular)
                        div_text_w = draw.textlength(text_content, font=div_font)
                        div_bbox = div_font.getbbox("Hg")
                        div_text_h = div_bbox[3] - div_bbox[1]

                        div_total_w = metrics.q_max_w * 0.5
                        center_x = metrics.q_x + metrics.q_max_w / 2
                        area_start_x = center_x - div_total_w * 0.75
                        area_end_x = center_x + div_total_w * 0.75
                        text_x = center_x - div_text_w / 2
                        text_gap = 8
                        div_mid_y = q_curr_y + padding_v + (div_text_h / 2)

                        left_line_end = text_x - text_gap
                        if left_line_end > area_start_x:
                            for lx in range(int(area_start_x), int(left_line_end), 4):
                                draw.point((lx, div_mid_y), fill=self.C_QUOTE)

                        draw.text(
                            (text_x, div_mid_y),
                            text_content,
                            font=div_font,
                            fill=self.C_QUOTE,
                            anchor="lm",
                        )

                        right_line_start = text_x + div_text_w + text_gap
                        if right_line_start < area_end_x:
                            for lx in range(int(right_line_start), int(area_end_x), 4):
                                draw.point((lx, div_mid_y), fill=self.C_QUOTE)

                        q_curr_y += padding_v + div_text_h + padding_v
                else:
                    use_small_font = "_" in spec
                    font_size = int(fonts["quote"].size * 0.8) if use_small_font else fonts["quote"].size
                    target_font = self._load_font(font_size, self.Regular) if use_small_font else fonts["quote"]
                    target_font_h = target_font.getbbox("高")[3] - target_font.getbbox("高")[1]

                    norm_spec = spec.replace("_", "-")
                    align = "left"
                    if ":-:" in norm_spec:
                        align = "center"
                    elif "-:" in norm_spec:
                        align = "right"

                    wrap_width = metrics.q_max_w * (1 if quote_parse.pure_center else 0.8)
                    margin_w = metrics.q_max_w * 0.1
                    wrapped_sub_lines, _ = self._process_text_wrapping(draw, text_content, target_font, wrap_width)

                    for sub_line in wrapped_sub_lines:
                        sub_line_width = draw.textlength(sub_line, font=target_font)
                        x_pos = metrics.q_x
                        if align == "center":
                            x_pos = (
                                metrics.q_x
                                + margin_w * int(not quote_parse.pure_center)
                                + (wrap_width - sub_line_width) / 2
                            )
                        elif align == "right":
                            x_pos = (metrics.q_x + metrics.q_max_w) - sub_line_width

                        draw.text((x_pos, q_curr_y), sub_line, font=target_font, fill=self.C_QUOTE)
                        q_curr_y += target_font_h * 1.6
            else:
                if not text_content:
                    q_curr_y += q_font_h * 1.6
                    continue

                wrapped_sub_lines, _ = self._process_text_wrapping(
                    draw,
                    text_content,
                    fonts["quote"],
                    metrics.q_max_w,
                )
                for sub_line in wrapped_sub_lines:
                    draw.text((metrics.q_x, q_curr_y), sub_line, font=fonts["quote"], fill=self.C_QUOTE)
                    q_curr_y += q_font_h * 1.6

        if mode == Mode.DAILY:
            self._draw_text_right(
                draw,
                "--来自 @" + payload.quote_source + " 的评论",
                fonts["quote_sub"],
                self.CONTENT_RIGHT_X,
                q_curr_y + 20,
                self.C_SUB,
            )

            bot_sep_y = mid_y + metrics.middle_h + 10
            self._draw_dot_line(draw, bot_sep_y)

            foot_base_y = bot_sep_y
            foot_y = foot_base_y + 24
            ct = "AMLL 亲友团 | 今日推荐"
            ct_bbox = draw.textbbox((0, 0), ct, font=fonts["footer_center"])
            draw.text(
                (self.MARGIN_SIDE + (self.CARD_W - (ct_bbox[2] - ct_bbox[0])) / 2, foot_y),
                ct,
                font=fonts["footer_center"],
                fill=self.C_FOOTER_CENTER,
            )
            return foot_base_y

        return sep_y

    def render_footer(
        self,
        draw: ImageDraw.ImageDraw,
        bg_img: Image.Image,
        metrics: LayoutMetrics,
        fonts: Dict[str, ImageFont.FreeTypeFont],
    ) -> None:
        outer_y = self.MARGIN_TOP + metrics.total_card_h + 20
        outer_right_x = self.MARGIN_SIDE + self.CARD_W
        outer_color = self.get_contrasting_text_color(
            bg_img.crop((self.W - 300, metrics.total_img_h - 80, self.W, metrics.total_img_h))
        )

        self._draw_text_right(
            draw,
            self.style.watermark_designed,
            fonts["footer_outer"],
            outer_right_x,
            outer_y,
            outer_color,
        )
        self._draw_text_right(
            draw,
            self.style.watermark_generated,
            fonts["footer_outer"],
            outer_right_x,
            outer_y + 30,
            outer_color,
        )

    async def generate(
        self,
        data: Union[CardPayload, Dict[str, Any]],
        inner_blurred: bool = False,
        show_qrcode: bool = False,
        mode: Union[str, Mode] = Mode.DAILY,
        http_client: Optional[HttpClient] = None,
    ) -> Image.Image:
        payload = _payload_from_any(data)
        safe_mode = _coerce_mode(mode)

        created_client = False
        client = http_client
        if client is None:
            created_client = True
            client = HttpClient(headers={"User-Agent": DEFAULT_USER_AGENT}, timeout=10, trust_env=True)
            await client.__aenter__()

        try:
            logger.info("下载封面: %s", payload.cover_url)
            cover_img_raw = (await download_image_with_fallback(payload.cover_url, client)).convert("RGB")
            theme_rgb = self.get_dominant_color(cover_img_raw)
            logger.info("识别主题色: %s", theme_rgb)

            try:
                fonts = self._prepare_fonts()
            except IOError:
                logger.error("字体加载失败: %s", self.font_path)
                return Image.new("RGB", (100, 100), color="red")

            quote_parse = QuoteParser.parse(payload.quote_content)
            metrics = self.measure_layout(payload, safe_mode, fonts, quote_parse, show_qrcode)
            bg_img, draw = self.render_background(cover_img_raw, metrics, inner_blurred)
            header_start_y = self.render_header(
                draw,
                bg_img,
                payload,
                metrics,
                fonts,
                show_qrcode,
                theme_rgb,
            )
            self.render_quote(
                draw,
                bg_img,
                payload,
                metrics,
                fonts,
                quote_parse,
                safe_mode,
                theme_rgb,
                header_start_y,
            )
            self.render_footer(draw, bg_img, metrics, fonts)
            return bg_img
        finally:
            if created_client:
                await client.__aexit__(None, None, None)

def _song_info_to_dict(song: Optional[SongInfo]) -> Optional[Dict[str, Any]]:
    if song is None:
        return None
    payload = {
        "title": song.title,
        "artist": song.artist,
        "cover_url": song.cover_url,
        "music_id": song.music_id,
    }
    if song.song_url:
        payload["song_url"] = song.song_url
    return payload


def _payload_from_any(data: Union[CardPayload, Dict[str, Any]]) -> CardPayload:
    if isinstance(data, CardPayload):
        return data
    return CardPayload(
        title=data.get("title", ""),
        artist=data.get("artist", ""),
        cover_url=data.get("cover_url", ""),
        quote_content=data.get("quote_content", ""),
        quote_source=data.get("quote_source", ""),
        date_obj=data.get("date_obj", datetime.now()),
        music_id=data.get("music_id"),
        song_url=data.get("song_url"),
    )


def from_html_escaped(text: str) -> str:
    return (
        text.replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&amp;", "&")
        .replace("&quot;", "\"")
        .replace("&#39;", "'")
    )


@lru_cache(maxsize=1)
def _build_emoji_regex() -> re.Pattern[str]:
    language_pack: Dict[str, str] = {
        data["en"]: em
        for em, data in emoji.EMOJI_DATA.items()
        if "en" in data and data["status"] <= emoji.STATUS["fully_qualified"]
    }
    emoji_regex = "|".join(map(re.escape, sorted(language_pack.values(), key=len, reverse=True)))
    return re.compile(emoji_regex)


def clean_emojis(text: str) -> str:
    return _build_emoji_regex().sub("�", text)


async def fetch_lines(music_id: str, platform: str) -> Optional[str]:
    safe_platform = _coerce_platform(platform)
    async with HttpClient(timeout=10, trust_env=True) as http_client:
        return await LyricsService().fetch(music_id, safe_platform, http_client)


def _parse_date_or_today(date_str: str) -> tuple[datetime, str]:
    try:
        date_obj = datetime.strptime(date_str, "%Y-%m-%d")
        return date_obj, date_str
    except ValueError:
        logger.warning("⚠️ 日期格式错误 (%s)，使用今日", date_str)
        date_obj = datetime.now()
        return date_obj, date_obj.strftime("%Y-%m-%d")


async def generate_card(req: CardRequest) -> CardResult:
    platform = _coerce_platform(req.platform)
    mode = _coerce_mode(req.mode)
    date_obj, normalized_date = _parse_date_or_today(req.date_str)

    provider = get_song_provider(platform, req.am_storefront)
    renderer = MusicCard(
        font_path=req.font_path,
        platform=platform,
        am_storefront=req.am_storefront,
        style=req.style,
        layout=req.layout,
    )

    final_song: Optional[SongInfo] = None
    daily_data: Optional[DailyRecommendation] = None
    quote_content: Optional[str] = None
    quote_source: str = ""

    try:
        async with HttpClient(timeout=15, trust_env=True) as http_client:
            if mode == Mode.DAILY:
                daily_data = await DailyRecommendationService().fetch(normalized_date, http_client)

            if daily_data:
                logger.info("成功获取每日推荐数据")
                rec_music_id = daily_data.music_id
                if rec_music_id:
                    final_song = await provider.fetch_song(str(rec_music_id), http_client)
                    if final_song:
                        cover = daily_data.cover_path
                        if cover and cover != "/tj/wfm.jpg":
                            if cover.startswith("/"):
                                final_song.cover_url = AMLL_BASE_URL + cover
                            else:
                                final_song.cover_url = cover

                if daily_data.comment:
                    quote_content = daily_data.comment
                if daily_data.username:
                    quote_source = daily_data.username
            else:
                if mode == Mode.DAILY:
                    logger.info("无每日推荐或获取失败，检查命令行参数...")

                if req.music_id:
                    final_song = await provider.fetch_song(req.music_id, http_client)
                elif req.song_info:
                    final_song = SongInfo(
                        title=req.song_info.title,
                        artist=req.song_info.artist,
                        cover_url=req.song_info.cover_url,
                        music_id=req.song_info.music_id or (req.music_id or "0"),
                        song_url=req.song_info.song_url,
                    )

            if not final_song:
                return CardResult(
                    success=False,
                    error_code="SONG_INFO_UNAVAILABLE",
                    message="错误: 无法获取歌曲信息 (Daily API 返回值为空, 且未提供有效 NCM ID 或 Info)",
                )

            if not quote_content:
                if mode == Mode.LYRIC:
                    if not final_song.music_id or final_song.music_id == "0":
                        return CardResult(
                            success=False,
                            error_code="LYRIC_MUSIC_ID_REQUIRED",
                            message="错误: lyric 模式需要有效 music_id",
                        )

                    lines = await LyricsService().fetch(final_song.music_id, platform, http_client)
                    if not lines:
                        return CardResult(
                            success=False,
                            error_code="LYRIC_UNAVAILABLE",
                            message="错误: 无法获取歌词内容",
                        )
                    quote_content = lines
                elif req.quote:
                    quote_content = req.quote.content.replace("\\n", "\n")
                    quote_source = req.quote.source
                else:
                    quote_content = "想要和你一起 一同实现远大的梦想"
                    quote_source = "RuriChan"

            song_url = final_song.song_url
            if not song_url and final_song.music_id and final_song.music_id != "0":
                song_url = provider.build_song_url(final_song.music_id, storefront=req.am_storefront)

            payload = CardPayload(
                title=final_song.title,
                artist=final_song.artist,
                cover_url=final_song.cover_url,
                quote_content=quote_content,
                quote_source=quote_source,
                date_obj=date_obj,
                music_id=final_song.music_id,
                song_url=song_url,
            )

            image = await renderer.generate(
                payload,
                inner_blurred=req.inner_blurred,
                show_qrcode=req.show_qrcode,
                mode=mode,
                http_client=http_client,
            )

            return CardResult(
                success=True,
                image=image,
                music_id=final_song.music_id or "0",
                message="ok",
            )
    except Exception as exc:
        logger.exception("生成音乐卡片时发生未处理异常")
        return CardResult(
            success=False,
            error_code="UNHANDLED_EXCEPTION",
            message=f"错误: {exc}",
        )


async def generate_music_card_process(
    platform: str,
    mode: str,
    date_str: str,
    music_id_arg: Optional[str] = None,
    info_arg: Optional[list] = None,
    quote_arg: Optional[list] = None,
    inner_blurred: bool = False,
    show_qrcode: bool = False,
    font_path: str = "PingFang.ttc",
    am_storefront: str = "cn",
) -> Optional[tuple[Image.Image, str]]:
    song_info = None
    if info_arg and len(info_arg) == 3:
        song_info = SongInfo(
            title=info_arg[0],
            artist=info_arg[1],
            cover_url=info_arg[2],
            music_id=music_id_arg or "0",
        )

    quote = None
    if quote_arg and len(quote_arg) == 2:
        quote = QuoteData(content=quote_arg[0], source=quote_arg[1])

    request = CardRequest(
        platform=_coerce_platform(platform),
        mode=_coerce_mode(mode),
        date_str=date_str,
        music_id=music_id_arg,
        song_info=song_info,
        quote=quote,
        inner_blurred=inner_blurred,
        show_qrcode=show_qrcode,
        font_path=font_path,
        am_storefront=am_storefront,
    )

    result = await generate_card(request)
    if not result.success or result.image is None:
        logger.error(result.message)
        return None
    return result.image, (result.music_id or "0")


async def main() -> None:
    parser = argparse.ArgumentParser(description="生成仿网易云音乐风格的音乐卡片")
    parser.add_argument("--platform", type=str, choices=["ncm", "qq", "am"], default="ncm", help="获取歌曲的平台 ncm/qq/am")
    parser.add_argument("--mode", type=str, choices=["daily", "card", "lyric"], default="daily", help="制卡模式")
    parser.add_argument("--date", type=str, default=datetime.now().strftime("%Y-%m-%d"), help="日期 YYYY-MM-DD")
    parser.add_argument("--info", nargs=3, metavar=("TITLE", "ARTIST", "COVER_URL"), help="手动指定歌曲信息")
    parser.add_argument("--quote", nargs=2, metavar=("CONTENT", "SOURCE"), help="引言内容与来源")
    parser.add_argument("--inner-blurred", action="store_true", help="卡片内部背景模糊")
    parser.add_argument("--qrcode", action="store_true", help="生成二维码")
    parser.add_argument("--music-id", type=str, help="歌曲 ID")
    parser.add_argument("--am-storefront", type=str, default="cn", help="Apple Music 商店地区 (默认 cn)")

    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(message)s")

    song_info = None
    if args.info and len(args.info) == 3:
        song_info = SongInfo(
            title=args.info[0],
            artist=args.info[1],
            cover_url=args.info[2],
            music_id=args.music_id or "0",
        )

    quote = None
    if args.quote and len(args.quote) == 2:
        quote = QuoteData(content=args.quote[0], source=args.quote[1])

    request = CardRequest(
        platform=_coerce_platform(args.platform),
        mode=_coerce_mode(args.mode),
        date_str=args.date,
        music_id=args.music_id,
        song_info=song_info,
        quote=quote,
        inner_blurred=args.inner_blurred,
        show_qrcode=args.qrcode,
        font_path="PingFang.ttc",
        am_storefront=args.am_storefront,
    )

    result = await generate_card(request)
    if not result.success or result.image is None:
        logger.error(result.message or "生成失败")
        raise SystemExit(1)

    music_id = result.music_id or "0"
    match _coerce_mode(args.mode):
        case Mode.LYRIC:
            filename = f"music_lyric_{music_id}.png"
        case Mode.CARD:
            filename = f"music_card_{music_id}.png"
        case Mode.DAILY:
            filename = f"music_card_{args.date}.png"

    result.image.save(filename)
    logger.info("图片保存成功: %s", filename)


if __name__ == "__main__":
    if sys.platform == "win32":
        asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
    asyncio.run(main())
